version: "3"
services:
  app:
    image: noopkat/electric-io
    container_name: electric-io
    command: npm run start
    ports: # Can override if you have port collisions with something else
      - 3000:3000
    environment: # Expose to docker environment override
      - SIMULATING=false
      - DEBUG
      - CONSUMER_GROUP
      - PLATFORM=azure
      - IOTHUB_CONNECTION_STRING=<IoTHubConnectionString>
      - EVENTTHUB_CONNECTION_STRING=<EventHubConnectionString>
      - EDIT_MODE=unlocked
    volumes: # For file editing, watching, etc
      - electric-io:/usr/app
      - /usr/app/node_modules
volumes:
  electric-io:
