version: '3'

services:
  app:
    build: .
    image: electic-io
    container_name: electric-io
    command: npm run start
    ports: # Can override if you have port collisions with something else
      - 3000:3000
    env_file: # Expose to docker environment
      - .env
    environment: # Expose to docker environment override
      - SIMULATING
      - DEBUG
      - CONSUMER_GROUP
    volumes: # For file editing, watching, etc
      - ./:/usr/app
      - /usr/app/node_modules
